// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQq3F3pSkV__MHR_h9L0nfz--u-vC41MI',
    appId: '1:370754411200:web:27efb5f686fa7601d52b25',
    messagingSenderId: '370754411200',
    projectId: 'xupchat',
    authDomain: 'xupchat.firebaseapp.com',
    storageBucket: 'xupchat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNnucMaKLl2ug4PW5Jhjtb4FgcIs6pbK4',
    appId: '1:370754411200:android:dfbca68c962bba79d52b25',
    messagingSenderId: '370754411200',
    projectId: 'xupchat',
    storageBucket: 'xupchat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3vKRNXw3-USM6tipV0sKIFtC5s5zHr6M',
    appId: '1:370754411200:ios:60944212846183f7d52b25',
    messagingSenderId: '370754411200',
    projectId: 'xupchat',
    storageBucket: 'xupchat.appspot.com',
    iosClientId: '370754411200-p8qc5esnl7570r0tr89ornribi4hgiia.apps.googleusercontent.com',
    iosBundleId: 'com.example.xupchat',
  );
}
